name: sail_routing_dart

description: A new dart package for sail routing.
version: 1.0.0
author: Casey Hillers, Nicholas Kalscheuer, Daniel Richards, Donovan Rost, William Walker
homepage:

dependencies:
    csv: ^4.0.3
    args: ^1.5.1
    quiver: ^2.0.1
    vector_math: ^2.0.8

environment:
  sdk: '>=2.0.0 <3.0.0'
